apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis
  namespace: banorte-apps
  labels:
    app: sentiment-analysis
  annotations:
    service.alpha.openshift.io/dependencies: '[{"name": "postgresql", "kind": "Service"}]'
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: sentiment-analysis
  sessionAffinity: None

